---
title: "maps"
author: "Saul Soto"
date: "2/18/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidycensus)
library(tidyverse)
census_api_key("ee6ba6904fb1ec6234c1db9c07ce18a74fe5b85c")
```

```{r map, include=FALSE, echo=FALSE}
racevars <- c(White = "B02001_002", 
              Black = "B02001_003", 
              Asian = "B02001_005",
              Hispanic = "B03003_003")

suffolk <- get_acs(geography = "tract",
                  variables = racevars, 
                  year = 2018,
                  state = "MA",
                  county = "Suffolk County",
                  geometry = TRUE,
                  summary_var = "B02001_001") 
```

```{r noecho, echo=FALSE}
suffolk %>%
  mutate(Percent = 100 * (estimate / summary_est)) %>%
  ggplot(aes(fill = Percent, color = Percent)) +
  facet_wrap(~ variable) +
  geom_sf() +
  scale_fill_viridis_c(direction = -1) +
  scale_color_viridis_c(direction = -1) +
  labs(title = "Racial geography of Suffolk County, Massachusetts",
       caption = "Source: American Community Survey 2014-2018") +
  theme_void()
```

